### ISSUE TITLE
lwjgl 3.0.0a support

### ISSUE THREAD

**Issue by Tillaert** [philcali/sbt-lwjgl-plugin#38]
In version 3, lwjgl changed the org name from "org.lwjgl.lwjgl" to "org.lwjgl". I can override this in my build.sbt. However, the lwjgl-utils package is not present in the 3.0.0a release. 

build.sbt:

seq(lwjglSettings: _*)

lwjgl.version := "3.0.0a"

lwjgl.org := "org.lwjgl"

sbt output:

[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  ::          UNRESOLVED DEPENDENCIES         ::
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  :: org.lwjgl#lwjgl_util;3.0.0a: not found
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
sbt.ResolveException: unresolved dependency: org.lwjgl#lwjgl_util;3.0.0a: not found

**Comment by philcali** [comment]
Hmm, interesting. It should be easy enough to conditionally load that dependency based on the version provided, but that'll require a small change in the plugin logic.

My time is pretty limited these days, so it'll be a little while before I can get to it. If you would like to take a crack at it, I'll gladly merge it in.

**Comment by Tillaert** [comment]
I'll spend some time on it this weekend.

**Comment by philcali** [comment]
Fixed. Thanks again for your help.
